### ISSUE TITLE
MinimumHeight not work on with Bottom appear

### ISSUE THREAD

**Issue by m3rLin0WoRK** [bryx-inc/BRYXBanner#100]
Hi, 

I have a issue with minimumHeight property.
If you show banner from bottom, this property not work (with Xcode inspector I see auto layout issue)

If shown from top, minimumHeight works ONLY IF show is used without view (passing nil)

Thank you

**Comment by nmanoogian** [comment]
Hi @m3rLin0WoRK, are you still having this issue? If so, could you send some examples of how you're using the `minimumHeight` property?

**Comment by m3rLin0WoRK** [comment]
Hi @alkaline9500, I haven't tried again, I used custom view for my purpose.

Thank u :)

**Comment by nmanoogian** [comment]
Sounds good; thanks for submitting!

**Comment by barfoon** [comment]
Noticing `minimumHeight` does not work when using either `.top` or `.bottom` also

**Comment by nmanoogian** [comment]
Thanks for letting us know! If you have time to investigate, code examples and PRs are always welcome.

**Comment by ashleyng** [comment]
I believe this might be an issue with xcode caching the development pods (which i've experienced before with other projects). I was able to successfully change `minimumHeightConstraint` after cleaning the build and then running the example app.
