### ISSUE TITLE
Lack of 'swift_version' in podspec file

### ISSUE THREAD

**Issue by rafalur** [bryx-inc/BRYXBanner#109]
Hi, 

I noticed you don't set `swift_version` property in your .podspec file. It causes compilation errors in mixed swift version projects. 

F.e. I have project written in swift 3.0. I build it however using Xcode 10 and new build system. When installing dependencies using cocoapods the latest version of BRYXBanner (0.8.2) has swift version set to 3.0 instead of 4.2 and doesn't compile. Other frameworks, event those using swift 4.2 compile properly.

**Comment by nmanoogian** [comment]
Hi @rafalur, thanks for letting us know! I just pushed up a new version (0.8.3) with the `swift_version` in the podspec. However, when I try to deploy the cocoapod, I get a 500 error. I'll try again in an hour or so.

**Comment by nmanoogian** [comment]
OK, looks like it pushed properly now. Thanks again for reporting this!

**Comment by rafalur** [comment]
Yep, it works fine now, thanks!

**Comment by nmanoogian** [comment]
Excellent -- thanks again for the report!
