### ISSUE TITLE
Change Status Bar Color?

### ISSUE THREAD

**Issue by lukecharman** [bryx-inc/BRYXBanner#14]
Detect how dark the BG color is, and change the status bar from black to white, or vice versa, automatically when showing and hiding?

That, or offer a way to display the alert over the status bar?

**Comment by harlanhaskins** [comment]
This is interesting, because iOS 9 deprecated `-[UIApplication setStatusBarStyle]`, instead opting for the `preferredStatusBarStyle` of `UIViewController`.

**Comment by harlanhaskins** [comment]
Also, I'd need a way to dynamically determine the new status bar style based on the tint color. Or make `Banner` have a `preferredStatusBarStyle` itself.

**Comment by harlanhaskins** [comment]
This has been implemented in the latest commit. A new pod version will be out in a few minutes.

Basically:

``` rust
banner.preferredStatusBarStyle = .Default
banner.adjustsStatusBarStyle = true
```

And the banner will animate changing the status bar style when it displays.

**Comment by harlanhaskins** [comment]
Thanks for the suggestion!
