### ISSUE TITLE
Calling show from obj-c, Swift-2.0 branch

### ISSUE THREAD

**Issue by aminiz** [bryx-inc/BRYXBanner#15]
The method is not available. It is not shown in the generated BRYXBanner-Swift.h
I am temporarily working around this by using the following class

```
import UIKit
import BRYXBanner

class MPTBanner: Banner {
    override func show(duration duration: NSTimeInterval?) {
        super.show(duration: duration)
    }

    func show() {
        super.show(duration: 3.0)
    }
}
```

**Comment by harlanhaskins** [comment]
Oof. Yeah, this isn't great. It's probably because of default arguments in Swift.

**Comment by harlanhaskins** [comment]
Duplicate of #18
