### ISSUE TITLE
User dismiss

### ISSUE THREAD

**Issue by vineethvijayan** [bryx-inc/BRYXBanner#17]
Is it possible to have a close button at the right end, so that the user can dismiss the notification?

**Comment by harlanhaskins** [comment]
BRYXBanner supports tap-to-dismiss and swipe-to-dismiss. They're both enabled by default.

**Comment by vineethvijayan** [comment]
I am using tap to navigate to view for which the notification is intended to.

Will it be possible to have a close button on right side so that user can dismiss the notification (Like in whatsapp)?

**Comment by harlanhaskins** [comment]
Potentially, though I'd want it to be configurable and not displayed by default.
I'd love a pull request!

**Comment by vineethvijayan** [comment]
I am not that good in swift, but let me try :)
