### ISSUE TITLE
Release CocoaPods version for Swift 2.0

### ISSUE THREAD

**Issue by AnthonyMDev** [bryx-inc/BRYXBanner#19]
Since the Xcode 7 GM seed was released, and we can now upload applications for iOS9, can we get an official release of this pod for Swift 2.0 please?

Thank you!

**Comment by harlanhaskins** [comment]
Absolutely! I'll do this now.

**Comment by AnthonyMDev** [comment]
Thanks @harlanhaskins, you da best! haha

**Comment by harlanhaskins** [comment]
Done!
