### ISSUE TITLE
cannot pod install

### ISSUE THREAD

**Issue by longxianlin** [bryx-inc/BRYXBanner#22]
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:
- `BRYXBanner` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in`rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in`block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in`resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in`analyze'

**Comment by BorjaCloobing** [comment]
any solution? i have installed many pods, but this one crashes in Banner.swift file, any idea?

**Comment by harlanhaskins** [comment]
I really have no idea. Maybe try updating CocoaPods and see if that helps?

`sudo gem install cocoapods`

**Comment by BorjaCloobing** [comment]
thanks for fast reply, i guess that is not the problem, as i installed new cocoapods yesterday, do you know if it needs an specific ios 8.? or xcode versión?

**Comment by harlanhaskins** [comment]
You should be using Xcode 7 at least, with the iOS 8 SDK for CocoaPods to work correctly with this podspec

**Comment by BorjaCloobing** [comment]
i guess is my Xcode then, i am using 6.3, thanks a lot.
