### ISSUE TITLE
Wrong width

### ISSUE THREAD

**Issue by MaxFrax** [bryx-inc/BRYXBanner#24]
Hi guys,
when I show the banner on a tableView it appears smaller than the tableView.
In the image the tableView is the yellow one and the banner obviously is the red one.
![simulator screen shot 26 set 2015 16 29 12](https://cloud.githubusercontent.com/assets/3145452/10118003/d1a2e8a0-646b-11e5-9286-0a112fde1b63.png)

**Comment by MaxFrax** [comment]
I found a little hack to avoid the problem, but it's not a real fix. I added a backgroundView (an UIView with the same frame of the tableView) on the tableView and then I showed the banner on the backgroundView.

**Comment by harlanhaskins** [comment]
That's very weird -- the Banner is created with leading and trailing constraints that don't use constants. Care to share the code you used?

**Comment by MaxFrax** [comment]
<pre>
import Foundation
extension UIView {
    func showError(title: String, subtitle: String, image: UIImage?){
        let banner = Banner(title: title, subtitle: subtitle, image: image, backgroundColor: UIColor.redColor(), didTapBlock: nil)
        banner.animationDuration = 1
        banner.show(self, duration: 2)
    }
}
</pre>

And in a UITableViewController

<pre>
self.tableView.showError("Impossibile caricare i dati dalla rubrica", subtitle: "", image: nil)
</pre>

**Comment by xdoug7** [comment]
+1
I'm with the same problem here. The banner is always fitting the text width.
Other hack that I found to avoid this:

`Banner(title: title, subtitle: subtitle).show(view: self.tableView.tableHeaderView)`

**Comment by nahouto** [comment]
same error here in  a UIViewController. The banner is set as label's intrisinc size

**Comment by harlanhaskins** [comment]
Is this still an issue? 😕

**Comment by johndpope** [comment]
this is related to uitableview hardcoding width of cells to 320 http://stackoverflow.com/questions/26373102/uitableview-cell-width-on-ios-8-stuck-at-320pt

in cellforrowat index try forcing the frame size

cell.frame = CGRectMake(0,
                        0,
                        self.tableView.frame.size.width,
                        cell.frame.size.height);

http://stackoverflow.com/questions/13025616/uitableviewcell-width-is-greater-than-uitableview-width
