### ISSUE TITLE
Using the same banner will cause an incorrect width

### ISSUE THREAD

**Issue by mosabelagha** [bryx-inc/BRYXBanner#25]
When using the **same** banner more than once, the width of the banner will shrink to the hug the text content. This is likely an issue of not resting the layout of the view. An example is below.
![bug png](https://cloud.githubusercontent.com/assets/7012241/10714305/63157418-7ab7-11e5-875c-82f0ada9f505.jpeg)

**Comment by VivienGiraud** [comment]
Same here !
Still no fix?

**Comment by mosabelagha** [comment]
I was going to try and look into it more to set a fix after my finals, which may be a while

**Comment by mosabelagha** [comment]
Currently my solution is to use a new one every time and set a flag to prevent other banners from overlaying themselves that gets set to true when the banner goes up and false when it gets dismissed.

**Comment by mosabelagha** [comment]
^oops, my mistake

**Comment by VivienGiraud** [comment]
I think my solution will be to use this one:
https://github.com/NZN/NZAlertView

**Comment by harlanhaskins** [comment]
Honestly, I don't like the idea of re-using banners. It's not a lot of allocation necessary, and it keeps the code much cleaner.
However, there should be some kind of `BannerManager` that handles queueing up banners.

**Comment by mosabelagha** [comment]
+1 to 'BannerManager' - it could be set to either reject new banners or queue up others, depending on the programmer's preference.

**Comment by harlanhaskins** [comment]
I'm gonna close this for now. Re-using banners isn't going to be supported.
