### ISSUE TITLE
Cannot load the underlying module

### ISSUE THREAD

**Issue by Treverr** [bryx-inc/BRYXBanner#28]
I installed this using CocoaPods and when i try to
 import BRYXBanner 

I get an error saying it cannot load the underlying module.

Any ideas?

**Comment by harlanhaskins** [comment]
What version of Xcode are you using?

**Comment by Treverr** [comment]
Version 7.1 (7B91b)

**Comment by harlanhaskins** [comment]
Try following the steps from this issue and see if it fixes yours:
https://github.com/Alamofire/Alamofire/issues/441

**Comment by Treverr** [comment]
Awesome, commenting out, running, then un-commenting worked!

Thank you!

**Comment by harlanhaskins** [comment]
Great! Usually these issues require deleting all your build stuff, cleaning the pods, and starting over. Glad it's working for you!
