### ISSUE TITLE
Allow customization of position (top or bottom)

### ISSUE THREAD

**Issue by mosabelagha** [bryx-inc/BRYXBanner#29]
Allow the option of positioning the banner to the top or bottom of the view. I've done this myself in a hacky way, but can make an actual solution whenever I have time

**Comment by askielboe** [comment]
I'm interested in this too. Would like the banner to show at the bottom instead of the top.

Care to share your hacky solution @mosabelagha ?

**Comment by mosabelagha** [comment]
@askielboe Yes I can share it but I'm very busy at the moment – if I don't post something this saturday just ping me again on this thread.

**Comment by askielboe** [comment]
Thanks! I ended up coding the feature myself. :)

See: #36

**Comment by sagaya** [comment]
Is there a work around positioning it?

**Comment by harlanhaskins** [comment]
That should be implemented. I merged @askielboe's PR
