### ISSUE TITLE
Make title and subtitle optional

### ISSUE THREAD

**Issue by AnthonyMDev** [bryx-inc/BRYXBanner#3]
First off, great library! Thank you!
I think it would be nice for the title and subtitle to be a optional parameters, and if either is nil, the other label should fill the entire banner.

**Comment by harlanhaskins** [comment]
I'd love to do this, but I'm fairly busy working on other things. A PR would be awesome!

**Comment by AnthonyMDev** [comment]
Totally understand. I'll look into it. Shouldn't be too hard. But I didn't want to put the time in if a PR wasn't going to get accepted.

**Comment by harlanhaskins** [comment]
Actually, I think this wouldn't be too difficult if, instead of using two labels, we used one label and NSAttributedString to individually style the title and subtitle.

**Comment by AnthonyMDev** [comment]
That makes sense, but I'm working with the layout constraints right now, and I've almost got it working anyways! I'll let you know what I come up with.

**Comment by AnthonyMDev** [comment]
Got it working! PR #5
