### ISSUE TITLE
Feature Proposal - Banner Templates

### ISSUE THREAD

**Issue by AnthonyMDev** [bryx-inc/BRYXBanner#31]
It would be nice to have some pre-made template banners that have a preset color and image for some common uses.

For example:
- Error - red with an error icon
- Warning - yellow with an error icon
- Success - green with a checkmark icon

I'd like to create a `BannerTemplateType` protocol and add a convenience initializer that takes a `BannerTemplateType` as a parameter.

Then, I would create a few structs that conform to `BannerTemplateType` for the pre-made templates. This allows users to easily create their own banner templates, or even make their custom error types conform to `BannerTemplateType` to be easily displayed.

@harlanhaskins I'd be willing to make a PR for this if you are interested. I wanted to get your thoughts on this before I started implementation.

**Comment by harlanhaskins** [comment]
I guess I think this would be simpler as an extension with static functions on `Banner`

Like:

``` swift
extension Banner {
    class func warning(text: String) {
        return Banner(title: "Warning", subtitle: text, image: UIImage(named: "Caution"), backgroundColor: UIColor.bryxYellowColor())
    }
}
```

**Comment by AnthonyMDev** [comment]
Hmm, that's a fair point @harlanhaskins . I hadn't even considered that. It probably would be easier. I like the idea of being able to pass around `BannerTemplateType` objects though. For instance, an `ErrorType` enum could conform to `BannerTemplateType` so you could show the right error message for any given error.

This also allows me to pass a `BannerTemplateType` into a function to display the banner at run-time, when I may not know what banner I want to use at compile time.

Chances are using an extension, I could always get the same functionality, but I feel like it would create cleaner code in many situations using a protocol, and much more flexible.

Additionally, a user can easily create extensions as you have above on their own right now if they need them, so adding the protocol does not stop you from doing so.

Thoughts?

**Comment by AnthonyMDev** [comment]
@harlanhaskins If you aren't interested in this feature, just let me know and we can close this. 
Using extensions is something that users can probably just implement on their own very easily, so I don't think we need to add anything to the library in that case.

I still think that have a protocol for this would be really helpful, and I'm willing to take the time to make a PR, but I understand if this is a feature you aren't interested in including.

**Comment by harlanhaskins** [comment]
Yeah, I'm just not really convinced it's worth the extra coverage in the library. The Banner API is fairly simple on purpose.

Thanks for the proposal though!

**Comment by AnthonyMDev** [comment]
You got it. Thanks
