### ISSUE TITLE
0.5.3 is can NOT install from Carthage

### ISSUE THREAD

**Issue by takuoka** [bryx-inc/BRYXBanner#32]
0.5.0 -> 0.5.3

wow!!
please fix!!! :sob: 

> xcodebuild: error: Scheme Pods-BRYXBanner is not currently configured for the build action.

**Comment by yuvalt** [comment]
Agreed, please fix :+1:

**Comment by harlanhaskins** [comment]
I don't personally use Carthage so I'm not sure a) how to fix this, or b) what causes this.

I'd welcome a PR to fix it.

Maybe this might help? https://github.com/antitypical/Result/issues/71

**Comment by yuvalt** [comment]
The Xcode project file is problematic. If you go to the Build Scheme, you see that the target is missing. I can try to take a look at it later.

**Comment by harlanhaskins** [comment]
I re-made the Xcode project. Try now?

**Comment by yuvalt** [comment]
I can confirm it's building successfully now. Thanks for the quick turnaround time! :+1:

**Comment by takuoka** [comment]
Wow, How did you success? :open_mouth: 

I can't install yet.

> github "bryx-inc/BRYXBanner"

↓

> **\* Checking out BRYXBanner at "0.5.3"

↓

> xcodebuild: error: Scheme Pods-BRYXBanner is not currently configured for the build action.

:sob:

**Comment by yuvalt** [comment]
try:
github "bryx-inc/BRYXBanner" "master"
