### ISSUE TITLE
Error on uploading to app store, no executable

### ISSUE THREAD

**Issue by adampilks** [bryx-inc/BRYXBanner#34]
I am using BRYX banner for a project and on uploading I get the message that `project.app/Frameworks/BRYXBanner.framework does not contain a bundle executable`

I am including BRYXBanner via cocoapods, and for development it has been fine,

**Comment by geekyfox90** [comment]
Same issue

**Comment by harlanhaskins** [comment]
I think this is the same CocoaPods issues as #35.
