### ISSUE TITLE
BRYXBanner.bundle: No such file or directory

### ISSUE THREAD

**Issue by askielboe** [bryx-inc/BRYXBanner#35]
Setup: `CocoaPods 1.0.0.beta.6` | `Xcode 7.3`

Seems that BRYXBanner.bundle lives in a subdirectory of BRYXBanner, whereas xcode expects to find it in the root of BRYXBanner.

This results in the following error when trying to build BRYXBanner:

```
error: /Users/askielboe/Library/Developer/Xcode/DerivedData/xxx/Build/Products/Debug-iphonesimulator/BRYXBanner/BRYXBanner.bundle: No such file or directory
```

![screen shot 2016-04-01 at 09 41 02](https://cloud.githubusercontent.com/assets/52106/14200821/e5201b62-f7ed-11e5-92c1-81250691ed2e.png)

Xcode looks for it here:

![screen shot 2016-04-01 at 09 41 42](https://cloud.githubusercontent.com/assets/52106/14200834/f379baba-f7ed-11e5-8afa-56100a694b56.png)

Moving the file manually in Finder (as above) seems to fix the issue..

Possibly related to #34

**Comment by AnthonyMDev** [comment]
This is a known issue in the current CocoaPods beta.

See: Cocoapods/#5082 CocoaPods/#5034

When `1.0.0.beta.7` is released, this should be fixed.

**Comment by harlanhaskins** [comment]
I think this is fixed. Closing for now. If this isn't fixed, please reopen and I'll investigate. Thanks!
