### ISSUE TITLE
calling from queues other than main queues

### ISSUE THREAD

**Issue by amosavian** [bryx-inc/BRYXBanner#38]
If you call show function from a queue other than main queue it won't display anything. the solution is to call UI related functions in main queue using GCD

**Comment by AnthonyMDev** [comment]
@harlanhaskins Do you think we should be dispatching to the main queue inside the `show()` method? Or should the user be required to dispatch to the main queue? I'm leaning towards dispatching inside the `show()` method.

**Comment by amosavian** [comment]
@AnthonyMDev I consider `show()` method as a `presentLocalNotificationNow()` replacement so it's better to implement the dispatching logic inside `show()` method.
But if you consider `show()` method as a UI interacting method then you can notice the programmer and do nothing. @harlanhaskins

**Comment by harlanhaskins** [comment]
I think the `show()` method is a UI method, and therefore the onus of dispatching should be on the programmer. The library doesn't know anything about your particular context, and so it's not 100% safe to explicitly dispatch it.
