### ISSUE TITLE
Not show image on banner

### ISSUE THREAD

**Issue by mhtranbn** [bryx-inc/BRYXBanner#45]
hi @adambinsz , this Not show image on banner.

**Comment by zntfdr** [comment]
[try this](https://github.com/Abhishekg219/BRYXBanner)

**Comment by harlanhaskins** [comment]
Can you show me some more code? It's hard to see what's going wrong here.

**Comment by quiKsilverItaly** [comment]
I used the version of @zntfdr , but now I migrated to Swift3 and have the same problem again. I also can't use the version of @zntfdr anymore, because of Swift3.

**Comment by harlanhaskins** [comment]
Discussion on this pull request is happening at PR #48. I'd like to get this merged, but not if it removes the image tinting behavior.
