### ISSUE TITLE
Banner not dismissing 

### ISSUE THREAD

**Issue by vishnu-mee** [bryx-inc/BRYXBanner#47]
Hi , I am using BRYXBanner to notify internet connectivity. Banner is presented as expected but it is not dismissing when i dismiss it manually. 

`
    func reachabilityChanged(note: NSNotification) {

```
    let banner = Banner(title: "User Offline !!!", subtitle: "Device seems to have lost its internet connection.", image: nil, backgroundColor: UIColor.yellowColor())
    banner.position = .Bottom
    banner.dismissesOnTap = false

    let reachability = note.object as! Reachability

    if reachability.isReachable() {
       banner.dismiss()
    } else {

        banner.show()
    }
}
```

`

**Comment by zntfdr** [comment]
hi @vishnu-mee every time `reachabilityChanged(_:)` is called you're creating a new Banner instance.

What you want to do is:
1. create a Banner instance **outside** that function.
2. call banner.show() and/or banner.dismiss() **inside** that function.

**Comment by harlanhaskins** [comment]
Hmm, I think it's fine to use a new instance whenever a function is called.
The problem is that you're instantiating it and immediately calling `dismiss()` before `show()`

You'll need to show the banner, then dismiss it after a certain amount of time. Alternatively:

``` swift
if !reachability.isReachable() {
    let banner = Banner(title: "User Offline !!!", subtitle: "Device seems to have lost its internet connection.", image: nil, backgroundColor: UIColor.yellowColor())
    banner.position = .Bottom
    banner.dismissesOnTap = false
    banner.show()
}
```
