### ISSUE TITLE
 banner.adjustsStatusBarStyle = true but needs to invoke as soon as it's dismissed

### ISSUE THREAD

**Issue by johndpope** [bryx-inc/BRYXBanner#50]
I have a dark / default status -

I show a banner that's blue - with white background.

eg.
banner.show(duration: 15.0)
banner.preferredStatusBarStyle = .LightContent
banner.adjustsStatusBarStyle = true

I hit dismiss.

It continues to show white.

After 15 seconds - it turn back to dark /default.

It maybe simpler to avoid tracking this - and let developer prescribe it.

eg. 

originalStatusBarStyle = 
preferredBarStyle  =

then have developer hard code it.

**Comment by AnthonyMDev** [comment]
Has anyone else had this same problem? We may just need to dispatch the call to set the `statusBarStyle` on the main queue again? That seems really odd to me though. Does anyone have any other ideas why this may be happening? @johndpope Would you be able to submit an example project for me to play with this bug on, or can we re-create this bug in the library's current example project?

I really like the functionality of the library automatically handling the status bar for us and don't really want to see it removed personally. I'd much rather us find a way to fix the bug.

**Comment by harlanhaskins** [comment]
I really like the functionality, too, but it's definitely advised against. For example, if you've got two apps in a split screen, the banner will affect both. I think we're just not encouraged to consider the status bar as an intrinsic part of our app.

**Comment by AnthonyMDev** [comment]
That's a really good point I hadn't considered. I think you've changed my mind on this one.

**Comment by johndpope** [comment]
Spring cleaning my old github issues. Thanks for your efforts here @AnthonyMDev
