### ISSUE TITLE
Image is not shown.

### ISSUE THREAD

**Issue by HackShitUp** [bryx-inc/BRYXBanner#55]
Nice code.
I saw the other issues and your reference to issue #45, but it doesn't help. UIImage is not shown, even when set with UIImage(named: "imageName") for the public required init parameters. Tried to re-render your code to UIImageView, but that doesn't work either.

**Comment by harlanhaskins** [comment]
Can you post some example code to reproduce this?

**Comment by ElaineErnstPrivate** [comment]
Hello

Is there a solution regarding this problem yet? I am also facing this problem..

**Comment by yarodevuci** [comment]
Set this  imageView.image = image
Delete this ->  imageView.image = shouldTintImage ? image?.withRenderingMode(.alwaysTemplate) : image

**Comment by harlanhaskins** [comment]
So, you can get the same net effect by setting

```
banner.shouldTintImage = false
```
