### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by adrimarti** [bryx-inc/BRYXBanner#56]
I am having issues using the Banner with CocoaPods, XCode8 and Swift3

**Comment by romero-ios** [comment]
I am also having issues with this! Using BRYXBanner with Cocoapods (Xcode 8 and Swift 3) and after trying to build my app, BRYXBanner shows 48 errors!

**Comment by harlanhaskins** [comment]
I need to push a new tag to cocoapods. I'll try to do this now

**Comment by romero-ios** [comment]
I do not know why, but when trying to run pod update i keep getting v0.5.2, but the latest version appears to be v0.6.1
I manually downloaded the updated pod spec file, told the pod file to locate the pod spec in my local directory and now the BRYXBanner is compiling and building successfully... Not sure if this is a fix or more of a workaround.

**Comment by AnthonyMDev** [comment]
@harlanhaskins Has the swift 3 version been pushed yet?

**Comment by harlanhaskins** [comment]
@AnthonyMDev I'm still having trouble with CocoaPods here. It's failing to compile -- seems it's using a Swift 2.3 compiler, when xcodebuild works fine.

**Comment by AnthonyMDev** [comment]
@harlanhaskins New feature in CocoaPods. You need to be using `1.1.0.rc.2` and then add a `swift-version` file in the root of your project (where the `podspec`  is). The file should just contain one line of text that reads `3.0`.

This will force the linter to use Swift 3.

**Comment by harlanhaskins** [comment]
This should be fixed with 0.7.0!

**Comment by AnthonyMDev** [comment]
0.7.0 has been to the master spec repo?

Thanks @harlanhaskins!

**Comment by harlanhaskins** [comment]
Yep -- should be up now!

**Comment by lws803** [comment]
Hi, I have problems with animations in the bryxbanner notifications. There is no drop down animation and instead the banner just appears instantly.

**Comment by ghost** [comment]
I have also problem with animation. Did someone solve it?

**Comment by harlanhaskins** [comment]
This was supposed to have been fixed by #51; are you sure you're using 0.7.0?

**Comment by harlanhaskins** [comment]
Does this work with 0.7.2?
