### ISSUE TITLE
Can i move the notification down above tabbar #18

### ISSUE THREAD

**Issue by sagaya** [bryx-inc/BRYXBanner#57]

**Comment by harlanhaskins** [comment]
As in, so it covers the tab bar, or it displays as if it's originating 'from' the tab bar?

**Comment by sagaya** [comment]
As if it is originating from the tab bar

**Comment by harlanhaskins** [comment]
`banner.position = .bottom`

**Comment by sagaya** [comment]
`Value of type Banner has no member position`

**Comment by harlanhaskins** [comment]
Are you using 0.6.3 or 0.7.2?

**Comment by sagaya** [comment]
0.5.2
