### ISSUE TITLE
Swift 2.3 release

### ISSUE THREAD

**Issue by jannemecek** [bryx-inc/BRYXBanner#58]
I see there's no working Swift 2.3 release as the iOS 10 animation fixes were bundled with the Swift 3 syntax changes. Is there any chance of doing a release for those of us who are sticking to Swift 2.3 for the time being?

**Comment by harlanhaskins** [comment]
Try using release 0.6.2! 😅

**Comment by jannemecek** [comment]
@harlanhaskins  iOS 10 animation fix is bundled with the Swift 3 release. shouldn't it be included in 0.6.2 too?

**Comment by harlanhaskins** [comment]
The existing fix is in 0.6.2. If that's not working for you, then I think it's a different issue :(

**Comment by jannemecek** [comment]
@harlanhaskins you backported the fix in 0.6.3, what I said does stand for 0.6.2 :)

**Comment by harlanhaskins** [comment]
😂 Off by one errors, eh?
