### ISSUE TITLE
BRYXBanner 0.7.0 carthage support

### ISSUE THREAD

**Issue by NBoymanns** [bryx-inc/BRYXBanner#59]
Today I tried to update my carthage BRYXBanner dependency to version 0.7.0 because I would like to use this great package with Swift 3. 
But after the command `carthage update BRYXBanner --platform iOS` I got the following error: 

`Skipped building BRYXBanner due to the error: 
Dependency "BRYXBanner" has no shared framework schemes for any of the platforms: iOS`

Hope someone can help me!

**Comment by makoni** [comment]
Got same error too

**Comment by makoni** [comment]
I've fixed it in #61 
You can use my fork until PR will be merged: https://github.com/makoni/BRYXBanner

**Comment by harlanhaskins** [comment]
Try building 0.7.1 now.

**Comment by NBoymanns** [comment]
Great job, problem Fixed in version 0.7.1
