### ISSUE TITLE
Display based on nav bar?

### ISSUE THREAD

**Issue by jshier** [bryx-inc/BRYXBanner#6]
I'm always on the lookout for a good banner framework, but one thing I always seem to need is the ability to display banners, not at the top of the screen, but underneath the nav bar. This would be something like Facebook's internet connection banner. Not really that common but it does make the banners a bit less invasive when the user can still interact with the nav bar while they're being displayed. Any interest in this feature or intention to build it?

**Comment by harlanhaskins** [comment]
I considered this -- maybe adding it as a subview of the current view controller and constraining it to `topLayoutGuide`. I'd love a PR!

Maybe a `func showInView(view: UIView)` or something.

**Comment by ashishawaghad** [comment]
think I forgot to add another change

```
override public func didMoveToSuperview() {
    super.didMoveToSuperview()
    if let superview = superview where bannerState != .Gone {
        commonConstraints = NSLayoutConstraint.constraintsWithVisualFormat("H:|[banner]|", options: .DirectionLeadingToTrailing, metrics: nil, views: ["banner": self]) as! [NSLayoutConstraint]
        superview.addConstraints(commonConstraints)
        let yOffset: CGFloat = -7.0 // Offset the bottom constraint to make room for the shadow to animate off screen.
        showingConstraint = NSLayoutConstraint(item: self, attribute: .Top, relatedBy: .Equal, toItem: superview, attribute: .Top, multiplier: 1.0, constant: yOffset)
        hiddenConstraint = NSLayoutConstraint(item: self, attribute: .Bottom, relatedBy: .Equal, toItem: superview, attribute: .Top, multiplier: 1.0, constant: yOffset)
    }
}
```

The constraints need to be with 'superview' and not 'window' as above

**Comment by ashishawaghad** [comment]
pardon me. This is my first pull request :]

**Comment by harlanhaskins** [comment]
If you just make the change and commit it, the pull request will be updated.

**Comment by ashishawaghad** [comment]
Done. Thanks.
