### ISSUE TITLE
*** Skipped building BRYXBanner due to the error:

### ISSUE THREAD

**Issue by NithyaVenkat** [bryx-inc/BRYXBanner#60]
**\* Fetching BRYXBanner
**\* Checking out BRYXBanner at "0.7.0"
**\* xcodebuild output can be found in /var/folders/nc/jrryg2gs72vg47hjnbsyhn700000gn/T/carthage-xcodebuild.HJxQDz.log
**\* Skipped building BRYXBanner due to the error:
Dependency "BRYXBanner" has no shared framework scheme

ran in to this error whicle upating the latest for iOS 10?

**Comment by makoni** [comment]
I've fixed it in #61 
You can use my fork until PR will be merged: https://github.com/makoni/BRYXBanner

**Comment by harlanhaskins** [comment]
PR merged. Sorry for the inconvenience! Try version 0.7.1.

**Comment by harlanhaskins** [comment]
Closing as a dupe of #59.
