### ISSUE TITLE
carthage update - framework error

### ISSUE THREAD

**Issue by NithyaVenkat** [bryx-inc/BRYXBanner#62]

**Comment by NithyaVenkat** [comment]
**\* Fetching BRYXBanner
**\* Checking out BRYXBanner at "0.7.1"
**\* xcodebuild output can be found in /var/folders/nc/jrryg2gs72vg47hjnbsyhn700000gn/T/carthage-xcodebuild.EkTMGC.log
**\* Building scheme "BRYXBanner" in BRYXBanner.xcworkspace
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:29:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:29:16: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:39:1: error: expressions are not allowed at the top level
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:39:5: error: consecutive statements on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:52:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:52:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:57:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:57:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:60:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:60:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:63:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:63:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:66:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:66:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:69:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:69:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:76:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:76:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:83:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:83:13: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:83:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:83:18: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:89:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:89:13: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:89:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:89:18: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:95:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:95:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:98:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:98:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:101:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:101:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:104:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:104:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:107:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:107:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:114:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:114:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:123:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:123:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:135:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:135:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:196:26: warning: extraneous '_' in parameter: 'recognizer' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:203:28: warning: extraneous '_' in parameter: 'recognizer' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:289:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:289:13: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:289:14: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:289:18: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:291:40: error: boolean condition requires 'where' to separate it from variable binding
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:307:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:307:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:328:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:328:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:328:20: warning: extraneous '_' in parameter: 'view' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:351:5: error: expected declaration
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:351:9: error: consecutive declarations on a line must be separated by ';'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:351:23: warning: extraneous '_' in parameter: 'oldStatusBarStyle' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:367:51: warning: extraneous '_' in parameter: 'format' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:373:38: warning: extraneous '_' in parameter: 'edgeInsets' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:385:34: warning: extraneous '_' in parameter: 'attribute' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:390:34: warning: extraneous '_' in parameter: 'attribute' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:395:34: warning: extraneous '_' in parameter: 'attribute' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:400:36: warning: extraneous '_' in parameter: 'attributes' has no keyword argument name
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:52:33: error: use of undeclared type 'TimeInterval'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:57:40: error: type 'UIStatusBarStyle' has no member 'lightContent'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:69:26: error: type 'UIColor' has no member 'white'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:83:23: error: overriding declaration requires an 'override' keyword
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:89:23: error: overriding declaration requires an 'override' keyword
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:157:5: warning: declaring a public initializer for an internal class
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:281:14: warning: declaring a public initializer for an internal class
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:289:24: error: overriding declaration requires an 'override' keyword
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:328:68: error: use of undeclared type 'TimeInterval'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:39:1: error: ambiguous use of 'open'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:116:57: error: use of unresolved identifier 'UIFontTextStyle'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:125:57: error: use of unresolved identifier 'UIFontTextStyle'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:138:34: error: type 'UIViewContentMode' has no member 'scaleAspectFit'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:41:23: error: type 'UIApplication' has no member 'shared'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:157:123: error: type 'UIColor' has no member 'black'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:212:28: error: type 'UISwipeGestureRecognizerDirection' has no member 'up'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:219:50: error: value of type 'UIImage' has no member 'withRenderingMode'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:224:29: error: type 'UIColor' has no member 'black'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:244:50: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: Int)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:254:75: error: type 'NSLayoutAttribute' has no member 'bottom'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:255:75: error: type 'NSLayoutAttribute' has no member 'top'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:262:49: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView, constant: Double)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:263:49: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:264:47: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: Double)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:265:47: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: _)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:272:141: error: type 'NSLayoutFormatOptions' has no member 'alignAllCenterY'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:292:62: error: type 'NSLayoutAttribute' has no member 'leading'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:297:67: error: type 'NSLayoutAttribute' has no member 'top'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:299:66: error: type 'NSLayoutAttribute' has no member 'bottom'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:301:67: error: type 'NSLayoutAttribute' has no member 'bottom'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:303:66: error: type 'NSLayoutAttribute' has no member 'top'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 /Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Pod/Classes/Banner.swift:316:29: error: type 'UIApplication' has no member 'shared'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:336:33: error: type 'UIApplication' has no member 'shared'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:338:11: error: type 'UIApplication' has no member 'shared'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:340:9: error: type 'UIView' has no member 'animate'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:353:9: error: type 'UIView' has no member 'animate'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:368:16: error: type 'NSLayoutConstraint' has no member 'constraints'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:373:67: error: type 'UIEdgeInsets' has no member 'zero'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:377:37: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView, constant: CGFloat)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:378:37: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView, constant: CGFloat)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:379:37: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView, constant: CGFloat)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:380:37: error: cannot invoke 'constraintWithAttribute' with an argument list of type '(_, _, to: UIView, constant: CGFloat)'
/Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift:387:115: error: type 'NSLayoutAttribute' has no member 'notAnAttribute'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Example/BRYXBanner.xcworkspace -scheme BRYXBanner -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 /Users/apple/Documents/SystemStatus/iOS10/SystemStatus/Carthage/Checkouts/BRYXBanner/Pod/Classes/Banner.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by harlanhaskins** [comment]
You're using Swift 2.3, not swift 3. You need to use BRYXBanner 0.6.2.

**Comment by NithyaVenkat** [comment]
Hi, 
Actually I have converted my existing source code to swift 3 and modified the source code accordingly.
Getting error only on BryxBanner update,

Do I need to modify anything on settings ?
