### ISSUE TITLE
MinimumOSVersion is invalid

### ISSUE THREAD

**Issue by treyrich** [bryx-inc/BRYXBanner#64]
Getting an error during submission to app store that states that the MinimumOSVersion needs to have a minimum value of 8.0.

**Comment by zntfdr** [comment]
This framework is now written in **Swift 3**_(.0)_, which is only supported by **Xcode 8**_(.0+)_ which, in turn, supports only **iOS 8+**.

So, yes, the README should now state "A lightweight dropdown banner for iOS **8**+.".

Please, feel free to submit a PR 😉

**Comment by treyrich** [comment]
Apple is not rejecting the binary based on what the readme says. 

MinimumOSVersion is an info.plist key. Because the IPHONEOS_DEPLOYMENT_TARGET is incorrectly set. This prohibits the project from being submitted to iTunes Connect because the value must be at least 8.0 in the submitted archive. 

I won't be able to submit a PR for at least a few hours, but if this hasn't been fixed by then I'll send one over.
