### ISSUE TITLE
Align labels Right to Left

### ISSUE THREAD

**Issue by MohyG** [bryx-inc/BRYXBanner#68]
Hi
I need to put labels on right side of the contentView for instance with trailing = 8 to contentView
but I couldn't do that with manipulating the visual constraints for contentView In Banner Class
I need some help with that, and it would be nice for the next version of BRYXBanner to support right to left alignment of elements to support right to left languages like Persian
thanks

**Comment by harlanhaskins** [comment]
Hmm...auto layout should handle automatic RTL. Apologies for not testing this 😞

If we set the label's text alignment to `.natural`, then it should 'just work'!
