### ISSUE TITLE
Is branch swift_2.3 still valid?

### ISSUE THREAD

**Issue by daver234** [bryx-inc/BRYXBanner#69]
Hi,

In project I'm using Swift 2.3.  Is your branch swift_2.3 still the one to use for Swift 2.3 support?

Thanks,
Dave

**Comment by harlanhaskins** [comment]
The 0.6.2 version is the last version that supports Swift 2.3 -- you can use that 😅

**Comment by ElaineErnstPrivate** [comment]
Hello,
I've been trying to install the swift 2.3 branch but it keeps failing. As soon as I run the project it is giving me the following error: "Failed to read file or folder".
Is there any additional work when running it with carthage?

I have added the cartfile and the runscript. I can also view the checkout files. Any ideas?
Thanks
Elaine

**Comment by tomatealbertini** [comment]
I am still using 0.5.2 version and it works well with Swift 2.3
