### ISSUE TITLE
Xcode 8, Swift 3 support

### ISSUE THREAD

**Issue by hongzhou85** [bryx-inc/BRYXBanner#72]
How to use in Xcode 8 and swift 3?

**Comment by harlanhaskins** [comment]
Just use version 0.7.2.

**Comment by bwake2012** [comment]
I get a warning:

file:///Users/_deleted path segment here_/Pods/Target%20Support%20Files/BRYXBanner/ResourceBundle-BRYXBanner-Info.plist: warning: Missing file: /Users/_deleted path segment here_/Pods/Target Support Files/BRYXBanner/ResourceBundle-BRYXBanner-Info.plist is missing from working copy

when using version 0.7.2 with CocoaPods 1.1.1

**Comment by ThoseGuysInTown** [comment]
So does this library work with swift 3?

**Comment by bwake2012** [comment]
It seems to. I ported my app to Swift 3. I spent a week chasing a problem with another CocoaPod. I'm about to start beta testing the ported version.

Bob

**Comment by harlanhaskins** [comment]
Hmm...did that warning go away when you `git add`ed it?
Glad to hear it's working for you! It's working for us via CocoaPods too.

**Comment by bwake2012** [comment]
I had to restore an older version of the file. It was somehow missing from my source tree. 

I also get a message from CocoaPods that ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES needs to be set to $(inherited). Xcode then warns that the project settings should be updated, which switches the setting to YES, which will then produce the CocoPods message. It may not be related to BRYXBanner specifically.
