### ISSUE TITLE
Change MinimumOSVersion to 8.0 to support Carthage builds

### ISSUE THREAD

**Issue by aalenliang** [bryx-inc/BRYXBanner#81]
At the moment Carthage can build BRYXBanner for iOS but since it targets iOS 7, the resulting application cannot be submitted to iTunes Connect.

https://github.com/Alamofire/Alamofire/issues/352

**Comment by harlanhaskins** [comment]
I agree with this. No real need to still support 7; if someone wants to submit this with 7 they can just copy the older file.

If you want to make this change in a PR, I'd appreciate it!

**Comment by aalenliang** [comment]
Wow, Thanks for the quick reply. I'll make the change soon.
