### ISSUE TITLE
Close all existing banners

### ISSUE THREAD

**Issue by maxmika** [bryx-inc/BRYXBanner#82]
Hey,
is it possible to have all displayed Banners removed in order to prevent overlapping Banners? This would especially be useful when working with alpha < 1 in background Colors...

Maybe there's an existing method I've overseen, but if not, is there a (simple) trick?

Thanks in advance!

**Comment by harlanhaskins** [comment]
Unfortunately there isn't something like that right now. You'll probably need to keep track of displayed Banners yourself. I briefly floated the idea of a BannerManager that keeps track of this. I'd appreciate a pull request if you're up for it! 😃
