### ISSUE TITLE
status bar doesn't restore it's original style when dismissing banner manually

### ISSUE THREAD

**Issue by eastsss** [bryx-inc/BRYXBanner#85]
if i'm using `adjustsStatusBarStyle = true` and dismiss banner manually(by tapping or swiping), it doesn't restore original status bar style, because `dismiss()` called without parameters in `didTap(_:)`/`didSwipe(_:)` method, so this functionality doesn't work as expected. May be we should somehow save `oldStatusBarStyle` inside, and restore later?

P.S. But there is also the case when multiple banners with different durations shown, and we need to restore status bar only when last one is dismissed(?)

Let me know your thoughts on this

**Comment by nmanoogian** [comment]
Good eye on this 👍 

You're right, your solution in #116 doesn't handle the "multiple banners" case but I still think that your proposed behavior is better than the current behavior.
