### ISSUE TITLE
Add option for removing transparency

### ISSUE THREAD

**Issue by ctews** [bryx-inc/BRYXBanner#9]
Hey guys,

first of all thanks for this nice component! Would be nice if you could add a public property which reflects the transparency of the view, because at the moment it seems to have an `alpha = 0.9` or similar which kind of looks weird depending on the underlying content.

Thank you! :)

Cheers,
Chris

**Comment by harlanhaskins** [comment]
You should be able to adjust the `alpha` property on your `Banner` instance. Let me know if that doesn't work for you, and if you think it might be a bug!
