### ISSUE TITLE
Setting TextColor makes icon appear black

### ISSUE THREAD

**Issue by cdepace** [bryx-inc/BRYXBanner#91]
I'm trying to customise the banner:

`let banner = Banner(title: message.title,
                                subtitle: message.subtitle,
                                image: UIImage(named:"bell"),
                                backgroundColor: Style.Notifications.bannerBackgroundColor)
            banner.titleLabel.font = Style.Notifications.bannerTitleFont
            banner.detailLabel.font = Style.Notifications.bannerSubtitleFont
            banner.textColor = Style.Notifications.bannerTitleTextColor
            banner.dismissesOnTap = true`

the line `banner.textColor = Style.Notifications.bannerTitleTextColor` seems affecting the icon which gets rendered as a black circle. Not sure if I'm missing someting

**Comment by MichaelNeas** [comment]
Hey @cdepace 

I just caught on to this repo now unfortunately but there is a property on banner you can set to false that will not apply the filter to the image.

Set: `banner.shouldTintImage = false`
