### ISSUE TITLE
Banner doesn't appears on IOs 11

### ISSUE THREAD

**Issue by fdsilva** [bryx-inc/BRYXBanner#97]
Hi Guys,

We use BRXY-Banner in our app, witch works perfectly on iOs 9.3 an 10, but we test it on iOs 11 this week and the banner doesen't appears.

Are you Guys, will give support to iOs 11?

Thanks in advance!

PS: Sorry by my english

**Comment by harlanhaskins** [comment]
Hi @fdsilva! We're using BRYXBanner successfully on iOS 11 with no issues -- could you give us an example of what's going wrong for you? Some code would also be helpful!

**Comment by harlanhaskins** [comment]
Oops, sorry, accidentally closed it.

**Comment by fdsilva** [comment]
Hi Guys,

We test it today and everything works perfect, thanks alot for the support

**Comment by harlanhaskins** [comment]
Great! Thanks for using BRYXBanner!
