### ISSUE TITLE
iPhone X: bottom banner is overlapping with home indicator

### ISSUE THREAD

**Issue by ramdroid** [bryx-inc/BRYXBanner#99]
Tested in the simulator: when banner is shown on top then it's alright, when shown on bottom it overlaps with the home indicator (outside the safe area).

**Comment by rajsingh1** [comment]
Check this link. It will help a lot!
https://novemberfive.co/blog/apple-september-event-iphonex-apps/

**Comment by Tom29** [comment]
@ramdroid have you found the way to fix this for iPhone X ?
